# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TodoList(object):
    def setupUi(self, TodoList):
        TodoList.setObjectName("TodoList")
        TodoList.resize(846, 688)
        self.centralwidget = QtWidgets.QWidget(TodoList)
        self.centralwidget.setObjectName("centralwidget")
        self.label_todo = QtWidgets.QLabel(self.centralwidget)
        self.label_todo.setGeometry(QtCore.QRect(120, 60, 121, 41))
        self.label_todo.setObjectName("label_todo")
        self.label_statues = QtWidgets.QLabel(self.centralwidget)
        self.label_statues.setGeometry(QtCore.QRect(140, 230, 61, 41))
        self.label_statues.setObjectName("label_statues")
        self.linetodo = QtWidgets.QLineEdit(self.centralwidget)
        self.linetodo.setGeometry(QtCore.QRect(120, 130, 601, 51))
        self.linetodo.setObjectName("linetodo")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(480, 300, 93, 56))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.submit = QtWidgets.QPushButton(self.splitter)
        self.submit.setObjectName("submit")
        self.show_todos = QtWidgets.QPushButton(self.splitter)
        self.show_todos.setObjectName("show_todos")
        self.ToDo = QtWidgets.QCheckBox(self.centralwidget)
        self.ToDo.setGeometry(QtCore.QRect(140, 290, 82, 20))
        self.ToDo.setObjectName("ToDo")
        self.InProgres = QtWidgets.QCheckBox(self.centralwidget)
        self.InProgres.setGeometry(QtCore.QRect(140, 320, 82, 20))
        self.InProgres.setObjectName("InProgres")
        self.Done = QtWidgets.QCheckBox(self.centralwidget)
        self.Done.setGeometry(QtCore.QRect(140, 350, 82, 20))
        self.Done.setObjectName("Done")
        self.list_todos = QtWidgets.QListWidget(self.centralwidget)
        self.list_todos.setGeometry(QtCore.QRect(120, 400, 601, 192))
        self.list_todos.setObjectName("list_todos")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(480, 370, 93, 25))
        self.clear.setObjectName("clear")
        TodoList.setCentralWidget(self.centralwidget)
        self.HomeWorkToDos = QtWidgets.QMenuBar(TodoList)
        self.HomeWorkToDos.setGeometry(QtCore.QRect(0, 0, 846, 26))
        self.HomeWorkToDos.setObjectName("HomeWorkToDos")
        TodoList.setMenuBar(self.HomeWorkToDos)
        self.statusBar = QtWidgets.QStatusBar(TodoList)
        self.statusBar.setObjectName("statusBar")
        TodoList.setStatusBar(self.statusBar)

        self.retranslateUi(TodoList)
        QtCore.QMetaObject.connectSlotsByName(TodoList)

    def retranslateUi(self, TodoList):
        _translate = QtCore.QCoreApplication.translate
        TodoList.setWindowTitle(_translate("TodoList", "MainWindow"))
        self.label_todo.setText(_translate("TodoList", "Add Todo:"))
        self.label_statues.setText(_translate("TodoList", "Statues:"))
        self.submit.setText(_translate("TodoList", "Submit"))
        self.show_todos.setText(_translate("TodoList", "Show Todos"))
        self.ToDo.setText(_translate("TodoList", "ToDo"))
        self.InProgres.setText(_translate("TodoList", "InProgres"))
        self.Done.setText(_translate("TodoList", "Done"))
        self.clear.setText(_translate("TodoList", "Clear"))
